env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
    tsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  max-len:
    - error
    - code: 100
      ignoreUrls: true
      ignoreRegExpLiterals: true
      ignorePattern: "^(\
        \\} from '\\S+'|\
          from '\\S+'|\
        import .* from '\\S+'|\
        [ ]*(export )?(async )?function .*|\
        [ ]*[a-zA-Z0-9]+=\\{[^}]*\\}\
        )$"
